# This is a basic workflow to help you get started with Actions

name: BoostChicken Pihole DoH Dockerbuild

# Controls when the action will run. 
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '00 12 1/15 * *'
      

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
          
      - name: get latest version
        run: export VERSION=$(curl --silent "https://api.github.com/repos/pi-hole/docker-pi-hole/releases/latest" | jq -r '.["tag_name"]')
      
      - name: docker check
        run: docker pull boostchicken/pihole:$VERSION
      -
        name: build pihole
        run: docker buildx build --platform=linux/amd64,linux/arm64 --build-arg VERSION=$VERSION run-pihole -t boostchicken/pihole:latest -t boostchicken:/pihole:$VERSION --push

