name: UDMP Podman

on:
  workflow_dispatch:
  push:
    paths:
      - 'podman-update/build/Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./podman-update/build/ --file Dockerfile --tag boostchicken:udmp-podman-$(date +%s)
    - name: Docker Extract
      uses: shrink/actions-docker-extract@v1
      with:
        # Docker Image to extract files from
        image: boostchicken:udmp-podman-$(date +%s)
        # Path (from root) to a file or directory within Image
        path: /tmp/release/.
    - name: Upload Podman Install
      uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.extract.outputs.destination }}
        name: podman-install.zip
 
