name: UDM Podman

on:
  workflow_dispatch:
  push:
    paths:
      - 'podman-update/build/Dockerfile'
  pull_request:
    paths:
      - 'podman-update/build/Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Build the Docker image
      run: docker build --file podman-update/build/Dockerfile --build-arg UDM_PLATFORM=UDM-Base --tag boostchicken:udm-podman podman-update/build/
    - name: Docker Extract
      id: extract
      uses: boostchicken-dev/actions-docker-extract@v3
      with:
        # Docker Image to extract files from
        image: boostchicken:udm-podman
        # Path (from root) to a file or directory within Image
        path: /tmp/install/.
        
    - name: Generate new tag version
      id: version
      uses: flynshue/version-action@v0.0.1
      
    - name: Upload Podman Install
      uses: actions/upload-artifact@v3.1.2
      with:
        path: ${{ steps.extract.outputs.destination }}
        name: podman-udm-${{ steps.version.outputs.version }}
        retention-days: 90
